version: "3.9"
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "4000:4000"
    env_file: ./backend/.env
    depends_on:
      - postgres
    restart: on-failure
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8081:80"
  postgres:
    container_name: postgres
    image: "postgres:12"
    ports:
      - "5432:5432"
    env_file: ./.env
    volumes:
      - ~/pg-data:/var/lib/postgresql/data/pgdata
    
    